# Generated by Django 5.2.6 on 2025-09-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="github_username",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitter_handle",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Profile picture", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Tell us about yourself", max_length=500
            ),
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
