# Generated by Django 5.2.6 on 2025-09-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="auto_detected_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="confidence_score",
            field=models.FloatField(
                blank=True, help_text="AI confidence in categorization", null=True
            ),
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS icon class or emoji", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="media.documentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="media.documentcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfile",
            index=models.Index(
                fields=["category"], name="media_docum_categor_6ff989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfile",
            index=models.Index(
                fields=["auto_detected_type"], name="media_docum_auto_de_f15d57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="media_docum_is_acti_758813_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcategory",
            index=models.Index(
                fields=["parent"], name="media_docum_parent__1c5329_idx"
            ),
        ),
    ]
