# Generated by Django 5.2.6 on 2025-09-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_documentfile_auto_detected_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentcategory",
            name="parent",
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="category",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("report", "Report"),
                    ("presentation", "Presentation"),
                    ("spreadsheet", "Spreadsheet"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.RemoveIndex(
            model_name="documentfile",
            name="media_docum_categor_6ff989_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentfile",
            name="media_docum_auto_de_f15d57_idx",
        ),
        migrations.RemoveField(
            model_name="documentfile",
            name="auto_detected_type",
        ),
        migrations.RemoveField(
            model_name="documentfile",
            name="confidence_score",
        ),
        migrations.DeleteModel(
            name="DocumentCategory",
        ),
    ]
