# Generated by Django 5.2.6 on 2025-09-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_delete_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="CSS icon class or emoji", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether posts with this status are publicly visible",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Post Status",
                "verbose_name_plural": "Post Statuses",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="blog_app_po_status__26835f_idx",
            old_name="blog_app_po_status_0298f4_idx",
        ),
        migrations.AddIndex(
            model_name="poststatus",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="blog_app_po_is_acti_8bf240_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="poststatus",
            index=models.Index(
                fields=["is_published"], name="blog_app_po_is_publ_d2534a_idx"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog_app.poststatus",
            ),
        ),
    ]
